defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-imagenet100-linear"
pretrained_feature_extractor: None
backbone:
  name: "resnet18"
pretrain_method: "simclr"
data:
  dataset: imagenet10
  train_path: "/projects/0/gusr0443/data/imagewoof2/train"
  val_path: "/projects/0/gusr0443/data/imagewoof2/val"
  format: "image_folder"
  num_workers: 4
  trainSplit: 'split1_D_i'
optimizer:
  name: "sgd"
  batch_size: 512
  lr: 1.0
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
