defaults:
  - _self_
  - augmentations: symmetric_weak.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mocov2plus-imagenet100"
method: "mocov2plus"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 128
  queue_size: 2048
  temperature: 0.05
  geometric_loss: False
momentum:
  base_tau: 0.99
  final_tau: 0.999
data:
  dataset: imagenet10
  train_path: "/projects/0/gusr0443/data/imagewoof2/train"
  val_path: "/projects/0/gusr0443/data/imagewoof2/val"
  format: "image_folder"
  num_workers: 4
  trainSplit: 'split1_D_i'
optimizer:
  name: "sgd"
  batch_size: 512
  lr: 0.3
  classifier_lr: 0.3
  weight_decay: 1e-4
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 400
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32
