python3 main_knn.py \
    --dataset cifar100 \
    --train_data_path ./datasets \
    --val_data_path ./datasets \
    --batch_size 16 \
    --num_workers 10 \
    --pretrained_checkpoint_dir $1 \
    --k 1 10 \
    --temperature 0.2 \
    --feature_type backbone projector \
    --distance_function euclidean cosine
